'use strict';

angular.module('adminlte.modules', [
    'main',
    'dashboard',
    'AdminDashBoardService',
    'account',
    'contact',
    'lead',
    'opportunity',
    'campaign',
    'quote',
    'contract',
    'category',
    'CategoryService',
    'login',
    'LoginService',
    'user',
    'UserService',
    'country',
    'CountryService',
    'supplier',
    'SupplierService',
    'approving_manager',
    'ApprovingManagerService',
    'department',
    'DepartmentService',
    'resource_library',
    'ResourceLibService',
    'log',
    'LogService',
    'proof_of_life',
    'ProofOfLifeService',
    'traveller',
    'TravellerService',
    'report',
    'ReportService',
    'track_manage',
    'TrackAndManageService',
    'risk_assessment',
    'RiskAssessmentService',
    'email_template',
    'EmailTemplateService',
    'medical_info',
    'MedicalService',
    'profile',
    'AdminProfileService',
    'department',
    'DepartmentService',
   
    
    

]);
